#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    sum_positive = 0
    sum_negative = 0
    sum_zero = 0
    for i in range(len(arr)):
        if arr[i] > 0:
            sum_positive = sum_positive +1
        elif arr[i] < 0:
            sum_negative = sum_negative +1
        else:
            sum_zero = sum_zero + 1  
                  
    print(sum_positive/len(arr))
    print(sum_negative/len(arr))
    print(sum_zero/len(arr))
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
